[package]
name = "mainapp"
version = "0.1.0"
authors = ["Yuriy Larin <yuriy.larin@gmail.com>"]
edition = "2021"
description = "Console client app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
async-trait = "0.1.58"
futures = "0.3"
btleplug = { version = "0.10.5", features = ["serde"] }

bitflags = "2.3.1"
thiserror = "1.0.40"
uuid = "1.3.3"
#static_assertions = "1.1.0"
tokio = { version = "1.28.2", features = ["rt", "sync"] }
tokio-stream = { version = "0.1.11", features = ["sync"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }


[dev-dependencies]
#pretty_env_logger = "0.4.0"
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread"] }