language: rust

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libdbus-1-dev

rust:
  - stable

script:
  - cargo build --verbose --all
#  - cargo test --verbose --all

#jobs:
#  allow_failures:
#    - rust: stable
#  fast_finish: true
#
#cache: cargo