name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/checkout@v2
    - name: Install cargo version
      uses: dtolnay/rust-toolchain@stable
    - name: Install cargo audit
      run: cargo install cargo-audit
    - name: Install btleplug libraries
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Show rust version
      run: cargo --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
#    - name: Run Clippy
#      run: cargo clippy --verbose --D warnings
#    - name: Audit
#      run: cargo audit
