name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Rust
      uses: actions/checkout@v4
    - name: Install cargo version
      uses: dtolnay/rust-toolchain@stable
    - name: Install cargo audit
      run: cargo install cargo-audit
    - name: Install dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install libdbus-1-dev
    - name: Show rust version
      run: cargo --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
#    - name: Run Clippy
#      run: cargo clippy -- --no-deps -Dwarnings
#    - name: Audit
#      run: cargo audit
