name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
